minimum_pre_commit_version: 1.21.0
repos:

# check commit message with commitcan
- repo: https://github.com/CommittedTeam/CommitCanvas
  rev: 9ee2c7736bf19f1d64758d0e945c60b0ef10053f
  hooks:
    - id: commitcanvas
      language: python
      stages: [commit-msg]
