minimum_pre_commit_version: 1.21.0
repos:

- repo: https://github.com/CommittedTeam/CommitCanvas
  rev: dd39c53f5b0bc1db6dd973529a50691488a1c740
  hooks:
    - id: commitcanvas
      language: python
      stages: [prepare-commit-msg]
      # args: ["--path","model"]
